export const FUN_FACTS = [
  "Clawford learned clawhammer before learning how to use a hammer.",
  "Clawford keeps his banjo perfectly tuned, except during dramatic entrances.",
  "Clawford’s favorite tuning is whichever one he just discovered.",
  "Clawford believes every problem has a five-string solution.",
  "Clawford can smell an out-of-tune string from across the room.",
  "Clawford’s tiny banjo picks are custom-made.",
  "Clawford calls practice sessions “important ferret business.”",
  "Clawford has never met a chord he wouldn’t investigate.",
  "Clawford prefers open G because it leaves more time for snacks.",
  "Clawford counts strings before bed instead of sheep.",
  "Clawford once hid a capo and then forgot where.",
  "Clawford considers silence an unusually long rest.",
  "Clawford’s tail keeps time when his foot gets tired.",
  "Clawford knows several scales and climbs all of them.",
  "Clawford never frets about frets.",
  "Clawford thinks every good tune deserves another variation.",
  "Clawford’s banjo case contains three picks and eight emergency snacks.",
  "Clawford can turn tuning into a full-length performance.",
  "Clawford always paws before changing key.",
  "Clawford describes wrong notes as unexpected improvisation.",
  "Clawford’s favorite interval is the one between meals.",
  "Clawford finds hidden notes faster than hidden socks.",
  "Clawford once played a duet with his own echo.",
  "Clawford believes a banjo belongs in every musical genre.",
  "Clawford’s whiskers twitch whenever someone mentions tablature.",
  "Clawford reads sheet music from left to right, usually.",
  "Clawford considers the fifth string small but mighty.",
  "Clawford practices rolls even when eating breakfast.",
  "Clawford has a chord for every mood.",
  "Clawford’s happy chord contains at least one open string.",
  "Clawford can play quietly, but rarely sees the point.",
  "Clawford thinks syncopation makes excellent exercise.",
  "Clawford once chased a runaway eighth note.",
  "Clawford keeps spare strings in a secret tunnel.",
  "Clawford’s metronome has learned to be patient.",
  "Clawford calls difficult passages “advanced opportunities.”",
  "Clawford can locate middle C without asking for directions.",
  "Clawford’s favorite key opens the door to another tune.",
  "Clawford believes every rest should include a snack.",
  "Clawford is fluent in notation, tablature, and enthusiastic squeaking.",
  "Clawford’s first composition was called “The Ballad of the Missing Sock.”",
  "Clawford warms up with cold mountain tunes.",
  "Clawford never plays second fiddle because he plays banjo.",
  "Clawford measures progress in tunes learned and treats earned.",
  "Clawford suspects diminished chords simply need encouragement.",
  "Clawford’s fastest tune is still waiting for a name.",
  "Clawford enjoys long walks along the fretboard.",
  "Clawford has strong opinions about bridge placement.",
  "Clawford believes good timing begins with arriving before the downbeat.",
  "Clawford occasionally tunes by ear and occasionally by whisker.",
  "Clawford thinks double C means twice the fun.",
  "Clawford calls sawmill tuning “music with extra mystery.”",
  "Clawford’s version of air banjo is surprisingly convincing.",
  "Clawford can make one note sound like the beginning of an adventure.",
  "Clawford stores melodies wherever ferrets normally store things.",
  "Clawford has never knowingly underplayed a final chord.",
  "Clawford’s musical influences include rain, trains, and rattling snack tins.",
  "Clawford taps his foot even when no music is playing.",
  "Clawford considers every staircase a musical scale.",
  "Clawford’s practice schedule includes several carefully timed naps.",
  "Clawford believes the best tunes leave room for mischief.",
  "Clawford can transpose a melody but not a heavy banjo case.",
  "Clawford once mistook a fermata for a tiny umbrella.",
  "Clawford regards tuning pegs as very small steering wheels.",
  "Clawford always checks the tuning before blaming the tablature.",
  "Clawford’s favorite dynamic marking is “playfully.”",
  "Clawford knows that sharp notes require careful handling.",
  "Clawford avoids flat notes by keeping them properly inflated.",
  "Clawford thinks a pickup is how someone carries his banjo.",
  "Clawford’s encore usually begins before the applause ends.",
  "Clawford has perfected the ancient art of looking busy while tuning.",
  "Clawford believes three chords can tell a thousand stories.",
  "Clawford gives every new banjo a thorough sniff test.",
  "Clawford’s tail has never missed a downbeat.",
  "Clawford sometimes dreams in arpeggios.",
  "Clawford can identify a G chord from its pawprints.",
  "Clawford keeps rhythm better than he keeps track of his belongings.",
  "Clawford thinks hammer-ons sound more dangerous than they are.",
  "Clawford prefers pull-offs that do not involve removing clothing.",
  "Clawford calls slides “the scenic route between notes.”",
  "Clawford knows that practice makes progressively better.",
  "Clawford’s banjo has heard every excuse for one more tune.",
  "Clawford treats accidental notes with kindness.",
  "Clawford believes musicians should always leave room for discovery.",
  "Clawford once found a melody hiding behind the fourth fret.",
  "Clawford uses harmonics to make his banjo sparkle.",
  "Clawford thinks rhythm is what keeps notes from bumping into each other.",
  "Clawford’s favorite chord progression always progresses toward snacks.",
  "Clawford considers a broken string an unscheduled intermission.",
  "Clawford knows when to improvise and when to consult the diagram.",
  "Clawford never rushes unless the tune specifically requests it.",
  "Clawford’s paws are small, but his repertoire is enormous.",
  "Clawford believes every beginner already knows their first open string.",
  "Clawford can turn a scale exercise into a dance tune.",
  "Clawford thinks music theory is practical magic.",
  "Clawford’s banjo is louder than his indoor voice.",
  "Clawford always leaves a little space between the notes for curiosity.",
  "Clawford considers curiosity the finest musical instrument.",
  "Clawford plays every tune like he has just uncovered it.",
  "Clawford is still searching for the legendary perfect chord."
];
